#!/usr/bin/env bash
# =============================================================================
# generate-keys.sh — Generate VLESS PQC encryption keys for the bridge
#
# Prerequisites: xray binary in PATH
#   curl -L https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
#
# Usage:
#   chmod +x generate-keys.sh
#   ./generate-keys.sh
#
# Outputs:
#   1. PQC decryption string for VPS2 inbound  (`xray vlessenc`)
#   2. PQC encryption string for VPS1→VPS2 bridge (`xray vlessenc -c`)
#
# NOTE: VLESS UUIDs are NOT generated here — they come from the Remnawave
#       panel: Users → user card → "Detailed Info" → copy VLESS UUID.
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if ! command -v xray &>/dev/null; then
    echo -e "${RED}ERROR: xray not found in PATH${NC}"
    echo "Download: https://github.com/XTLS/Xray-core/releases/latest"
    exit 1
fi

echo "============================================="
echo "  VLESS PQC Key Generator"
echo "============================================="
echo ""

# ---- PQC server-side decryption for VPS2 inbound ----
echo -e "${GREEN}=== VPS2 Server — VLESS PQC Decryption ===${NC}"
echo ""

SERVER_DECRYPT=$(xray vlessenc 2>/dev/null)

echo "Paste this into vps2-exit-node.jsonc → settings.decryption:"
echo ""
echo -e "  ${YELLOW}${SERVER_DECRYPT}${NC}"
echo ""

# ---- PQC client-side encryption for VPS1→VPS2 bridge outbound ----
echo -e "${GREEN}=== VPS1 Bridge Client — VLESS PQC Encryption ===${NC}"
echo ""

BRIDGE_ENCRYPT=$(xray vlessenc -c 2>/dev/null)

echo "Paste this into vps1-edge-node.jsonc → VLESS_TO_VPS2.users[0].encryption:"
echo ""
echo -e "  ${YELLOW}${BRIDGE_ENCRYPT}${NC}"
echo ""

# ---- VLESS UUID reminder ----
echo -e "${GREEN}=== VLESS UUIDs — from Remnawave panel ===${NC}"
echo ""
echo "NOT generated by this script."
echo ""
echo "Path: Remnawave → Users → <user> → More Actions → Detailed Info"
echo "  - Bridge user UUID → paste into vps2-exit-node.jsonc  (clients[].id)"
echo "  - Bridge user UUID → paste into vps1-edge-node.jsonc  (VLESS_TO_VPS2.users[].id)"
echo "  - Client user UUID → paste into client-template.jsonc (vnext[].users[].id)"
echo ""

# ---- Save to file ----
OUTPUT_FILE="$(dirname "$0")/../configs/generated-keys.txt"
cat > "$OUTPUT_FILE" <<EOF
Generated: $(date)
=============================================

VPS2 Server decryption (paste into vps2-exit-node.jsonc → settings.decryption):
${SERVER_DECRYPT}

VPS1 Bridge Client encryption (paste into vps1-edge-node.jsonc → VLESS_TO_VPS2.users[0].encryption):
${BRIDGE_ENCRYPT}

VLESS UUIDs are NOT here — get them from the Remnawave panel:
  Users → user card → More Actions → Detailed Info → copy UUID.
EOF

echo -e "${GREEN}Keys saved to: ${OUTPUT_FILE}${NC}"
